create table USUARIO (
	ID_USUARIO int AUTO_INCREMENT,
	NOMBRE varchar(45) not null unique,
	PASSWORD varchar(45) not null,
	ACTIVO bit not null,
	PRIMARY KEY (ID_USUARIO));

create table USUARIO_ROL (
  ID_USUARIO_ROL int not null,
  ID_USUARIO int not null,
  ROL varchar(45) not null,
  PRIMARY KEY (ID_USUARIO_ROL),
  UNIQUE KEY (ID_USUARIO, ROL),
  CONSTRAINT FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO));

INSERT INTO USUARIO(ID_USUARIO,NOMBRE,PASSWORD,ACTIVO)
VALUES (1,'oscar','123456', true);
INSERT INTO USUARIO(ID_USUARIO,NOMBRE,PASSWORD,ACTIVO)
VALUES (2,'alex','123456', true);

INSERT INTO USUARIO_ROL (ID_USUARIO_ROL, ID_USUARIO, ROL)
VALUES (1, 1, 'ROLE_USER');
INSERT INTO USUARIO_ROL (ID_USUARIO_ROL, ID_USUARIO, ROL)
VALUES (2, 1, 'ROLE_ADMIN');
INSERT INTO USUARIO_ROL (ID_USUARIO_ROL, ID_USUARIO, ROL)
VALUES (3, 2, 'ROLE_USER');