package com.patitodehule.plantillaweb.model;
// Generated May 5, 2017 10:54:13 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UsuarioRol generated by hbm2java
 */
@Entity
@Table(name = "USUARIO_ROL", catalog = "prueba", uniqueConstraints = @UniqueConstraint(columnNames = { "ID_USUARIO",
		"ROL" }))
public class UsuarioRol implements java.io.Serializable {

	private int idUsuarioRol;
	private Usuario usuario;
	private String rol;

	public UsuarioRol() {
	}

	public UsuarioRol(int idUsuarioRol, Usuario usuario, String rol) {
		this.idUsuarioRol = idUsuarioRol;
		this.usuario = usuario;
		this.rol = rol;
	}

	@Id

	@Column(name = "ID_USUARIO_ROL", unique = true, nullable = false)
	public int getIdUsuarioRol() {
		return this.idUsuarioRol;
	}

	public void setIdUsuarioRol(int idUsuarioRol) {
		this.idUsuarioRol = idUsuarioRol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USUARIO", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "ROL", nullable = false, length = 45)
	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

}
